#!/usr/bin/env bash
# A Bash script that transfers a file from a client to a server:

if [ $# -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

FILE_PATH="$1"
SERVER_IP="$2"
USERNAME="$3"
SSH_KEY="$4"

echo "Transferring file $FILE_PATH to server $SERVER_IP..."

scp -o "StrictHostKeyChecking=no" -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP:~/"

echo "File transfer complete."

