#!/usr/bin/env bash

# Install Nginx
apt-get update
apt-get -y install nginx

# Configure Nginx
echo "server {
    listen 80;
    root /var/www/html;
    index index.html;
    location / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx
service nginx restart

